language: node_js
node_js:
  - "6"
os:
  - linux
install:
  - sudo yum install cairo cairo-devel cairomm-devel libjpeg-turbo-devel pango pango-devel pangomm pangomm-devel giflib-devel
  - npm install
cache:
  directories:
  - node_modules
after_success:
  - npm run lint