language: node_js
node_js:
  - "6"
os:
  - linux
install:
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
  - npm install
cache:
  directories:
  - node_modules
after_success:
  - npm run lint